import os

#variables
BOT_TOKEN = os.environ['TOKEN']
WEATHER_API_KEY = os.environ['WEATHER API KEY']
TWITTER_BEARER_TOKEN = os.environ['TWITTER BEARER TOKEN']
TWITTER_SECRET_API_KEY = os.environ['TWITTER SECRET API KEY']
TWITTER_API_KEY = os.environ['TWITTER API KEY']
TWITTER_ACCESS_TOKEN_SECRET = os.environ['TWITTER ACCESS TOKEN SECRET']
TWITTER_ACCESS_TOKEN = os.environ['TWITTER ACCESS TOKEN']